version: '3.8'
services:    
  otel-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
      - --feature-gates=service.profilesSupport
    volumes:
      - /root/monitoring/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - 13133:13133  # health_check extension
      - 4317:4317  # OTLP gRPC receiver
      - 4318:4318  # OTLP http receiver
      - 1888:1888  # pprof extension
    # networks:
    #   - proxy
    depends_on:
      - loki
      - tempo
      - prometheus

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    # networks:
    #   - proxy
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      # - --web.enable-remote-write-receiver
      - --enable-feature=remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - /root/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml

  pyroscope:
    image: grafana/pyroscope:1.14.0
    container_name: pyroscope
    user: "0:0" 
    ports:
      - "4040:4040"  # Web UI
      - "4041:4041"  # Profiling server (OTLP / ingest)
    volumes:
      - pyroscope-data-1:/data/pyroscope
      - /root/monitoring/pyroscope-config.yaml:/etc/pyroscope/server.yml
    environment:
      PYROSCOPE_URL: http://pyroscope:4040
      LISTEN_PORT: 4041
    command:
      - --config.file=/etc/pyroscope/server.yml
      - --config.expand-env=true
    restart: unless-stopped
    # networks:
    #   - proxy

  loki:
    restart: unless-stopped
    image: grafana/loki:latest
    container_name: grafana-loki
    ports:
      - 3100:3100
    # networks:
    #   - proxy
    env_file:
      - stack.env
    volumes: [/root/monitoring/loki-config.yaml:/etc/loki/local-config.yaml]
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true

  tempo:
    restart: unless-stopped
    image: grafana/tempo:latest
    container_name: grafana-tempo
    env_file:
      - stack.env
    # ports:
    #   - "3200:3200"
    # networks:
    #   - proxy
    volumes: [/root/monitoring/tempo-config.yaml:/etc/tempo/tempo-config.yaml]
    command: -config.file=/etc/tempo/tempo-config.yaml -config.expand-env=true

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    container_name: grafana
    ports: [3005:3000]
    env_file:
      - stack.env
    # networks:
    #   - proxy

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - stack.env
    environment:
      - DATA_SOURCE_NAME=${POSTGRES_PROD_DATABASE_URL}
    restart: unless-stopped

# networks:
#   proxy:
#     external: true
#     name: proxy

volumes:
  pyroscope-data-1:
  # minio_data:
  # prometheus_data:


  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--path.rootfs=/rootfs'
  #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  #  # networks:
  #  #   - proxy
  #   restart: unless-stopped

  # db-postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter:latest
  #   container_name: kai-postgres-exporter
  #   env_file:
  #     - stack.env
  #   environment:
  #     - DATA_SOURCE_NAME=${KAI_DATABASE_URL}
  #  # networks:
  #  #   - proxy
  #   restart: unless-stopped
  
