remotecfg {
  url            = env("GCLOUD_FM_URL")
  id             = env("GCLOUD_FM_HOSTED_ID")
  poll_frequency = env("GCLOUD_FM_POLL_FREQUENCY")

  basic_auth {
    username = env("GCLOUD_FM_HOSTED_ID")
    password = env("GCLOUD_RW_API_KEY")
  }

  # attributes = {
  #   "hostname" = env("ALLOY_NODE_NAME")
  # }
}

otelcol.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:4317"
  }

  http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otelcol.exporter.prometheus.default.input]
    logs    = [otelcol.exporter.loki.default.input]
  }
}

otelcol.exporter.prometheus "default" {
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    url = env("GCLOUD_HOSTED_METRICS_URL")

    basic_auth {
      username = env("GCLOUD_HOSTED_METRICS_ID")
      password = env("GCLOUD_RW_API_KEY")
    }
  }
}

otelcol.exporter.loki "default" {
  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = env("GCLOUD_HOSTED_LOGS_URL")

    basic_auth {
      username = env("GCLOUD_HOSTED_LOGS_ID")
      password = env("GCLOUD_RW_API_KEY")
    }
  }
}
