name: hdx-oss
# OTEL_AGENT_FEATURE_GATE_ARG='--feature-gates=clickhouse.json'
# BETA_CH_OTEL_JSON_SCHEMA_ENABLED="true"
services:
  db:
    image: mongo:5.0.14-focal
    env_file:
      - stack.env
    volumes:
      - mongo_data:/data/db
    restart: on-failure

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - --config=/etc/otel-collector-config.yaml
      - --feature-gates=service.profilesSupport
    ports:
      - 4317:4317
      - 4318:4318

  hyperdx-otel-collector:
    image: docker.hyperdx.io/hyperdx/hyperdx-otel-collector:latest
    env_file:
      - stack.env
    environment:
      CLICKHOUSE_ENDPOINT: "tcp://ch-server:9000?dial_timeout=10s"
      HYPERDX_OTEL_EXPORTER_CLICKHOUSE_DATABASE: default
      HYPERDX_LOG_LEVEL: debug
      OPAMP_SERVER_URL: "http://app:4320"

    restart: on-failure
    depends_on:
      - ch-server
      - app

  app:
    image: docker.hyperdx.io/hyperdx/hyperdx:latest
    ports:
      - "9100:8000"
      - "5050:8080"
      - "4320:4320"
    env_file:
      - stack.env
    environment:
      MONGO_URI: "mongodb://db:27017/hyperdx"
      SERVER_URL: http://app:8000
      OPAMP_PORT: 4320
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://hyperdx-otel-collector:4318"
      OTEL_SERVICE_NAME: "hdx-oss-app"
      USAGE_STATS_ENABLED: "true"
      DEFAULT_CONNECTIONS: '[{"name":"Local ClickHouse","host":"http://ch-server:8123","username":"default","password":""}]'
    depends_on:
      - ch-server
      - db
    restart: on-failure

  ch-server:
    image: clickhouse/clickhouse-server:25.6-alpine
    ports:
      - "8124:8123"
    env_file:
      - stack.env
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - /root/ClickStack/docker/clickhouse/local/config.xml:/etc/clickhouse-server/config.xml
      - /root/ClickStack/docker/clickhouse/local/users.xml:/etc/clickhouse-server/users.xml
    restart: on-failure

volumes:
  mongo_data:
  clickhouse_data:
  clickhouse_logs:
