---
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
      grpc:
        endpoint: 0.0.0.0:4317

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/ready"

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

exporters:
  otlphttp/hdx:
    endpoint: "http://hyperdx-otel-collector:4338"
    headers:
      authorization: ${HDX_API_KEY}
    compression: gzip

service:
  telemetry:
    metrics:
      level: basic

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/hdx]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/hdx]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/hdx]
